---
- name: Run fs operations
  ansible.builtin.include_tasks: fs.yaml

- name: Configure redis
  ansible.builtin.include_tasks: configure.yaml

- name: Include Ubuntu specific tasks
  ansible.builtin.include_tasks: ubuntu.yaml
  when: OS == 'Ubuntu'
