---
- name: Check to see if systemd assets are still around
  ansible.builtin.stat:
    path: /lib/systemd/system/airflow-scheduler.service
  register: scheduler_service
  become: true

- name: Check to see if systemd assets are still around
  ansible.builtin.stat:
    path: /lib/systemd/system/airflow-api-server.service
  register: api_server_service
  become: true

- name: Check to see if systemd assets are still around
  ansible.builtin.stat:
    path: /lib/systemd/system/airflow-triggerer.service
  register: triggerer_service
  become: true

- name: Check to see if systemd assets are still around
  ansible.builtin.stat:
    path: /lib/systemd/system/airflow-dag-processor.service
  register: dag_processor_service
  become: true

- name: Stop airflow scheduler
  ansible.builtin.systemd:
    state: stopped
    enabled: false
    name: airflow-scheduler
  become: true
  when: scheduler_service.stat is defined and scheduler_service.stat.exists

- name: Stop airflow api server
  ansible.builtin.systemd:
    state: stopped
    enabled: false
    name: airflow-api-server
  become: true
  when: api_server_service.stat is defined and api_server_service.stat.exists

- name: Remove airflow triggerer service
  ansible.builtin.file:
    path: /lib/systemd/system/airflow-triggerer.service
    state: absent
  become: true
  when: triggerer_service.stat is defined and triggerer_service.stat.exists

- name: Remove airflow dag processor service
  ansible.builtin.file:
    path: /lib/systemd/system/airflow-dag-processor.service
    state: absent
  become: true
  when: dag_processor_service.stat is defined and dag_processor_service.stat.exists

- name: Reload daemon files
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
