---
AIRFLOW_LOCATION: internal
AIRFLOW_TIMEZONE: America/New_York

AIRFLOW_APISERVER_PORT: 8100
AIRFLOW_SCHEDULER_PORT: 8101
AIRFLOW_FLOWER_PORT: 8200
AIRFLOW_WORKER_LOG_SERVER_PORT: 8103
AIRFLOW_TRIGGER_LOG_SERVER_PORT: 8104
AIRFLOW_SCHEDULER_HEALTHCHECK_PORT: 8105

AIRFLOW_POSTGRES_HOST: 127.0.0.1
AIRFLOW_POSTGRES_PORT: 8102
AIRFLOW_REDIS_PORT: 7800

# To Set
AIRFLOW_FERNET_KEY:
AIRFLOW_SECRET_KEY:
AIRFLOW_SMTP_HOST:
AIRFLOW_SMTP_USER:
AIRFLOW_SMTP_PASSWORD:
AIRFLOW_SMTP_PORT:
