---
AIRFLOW_LOCATION: internal
AIRFLOW_TIMEZONE: America/New_York

AIRFLOW_FERNET_KEY:
AIRFLOW_SECRET_KEY:

AIRFLOW_SHAREDRIVE_DOMAIN:

AIRFLOW_SMTP_HOST:
AIRFLOW_SMTP_USER:
AIRFLOW_SMTP_PASSWORD:
AIRFLOW_SMTP_PORT:
