---
dependencies:
  - role: base

galaxy_info:
  role_name: nginx
  author: 1kbgz
  description: Install custom built NGINX with support for SPNEGO
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Ubuntu
  galaxy_tags:
    - development
