---
- name: Reload daemon files
  ansible.builtin.systemd:
    daemon_reload: true
    force: true

- name: Restart celery worker
  ansible.builtin.systemd:
    name: "airflow-celery-worker"
    state: restarted
    enabled: true
