---
dependencies: []

galaxy_info:
  role_name: postgresql_remove
  author: 1kbgz
  description: Remove PostgreSQL and undo configuration
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Ubuntu
  galaxy_tags:
    - development
