---
dependencies:
  - role: base
  - role: users

galaxy_info:
  role_name: airflow_common
  author: 1kbgz
  description: Install prerequisites and virtualenv for airflow
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
