---
dependencies: []

galaxy_info:
  role_name: airflow_celery_flower_remove
  author: 1kbgz
  description: Remove airflow_celery_flower and unconfigure
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
