---
- name: Stop and disable nginx service
  ansible.builtin.include_tasks: service.yaml

- name: Remove nginx packages
  ansible.builtin.include_tasks: deps.yaml

- name: Remove filesystem artifacts
  ansible.builtin.include_tasks: fs.yaml
