---
dependencies:
  - role: base
  - role: nginx

galaxy_info:
  role_name: redis
  author: 1kbgz
  description: Install Redis
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
