---
dependencies:
  - role: base
  - role: postgresql
  - role: airflow_common

galaxy_info:
  role_name: airflow_db
  author: 1kbgz
  description: Install database for airflow
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
