---
packages:
  EL:
    - autoconf
    - automake
    - boost-devel
    - cmake
    - cron
    - curl
    - git
    - git-lfs
    - htop
    - java-11-openjdk-devel
    - krb5-server
    - krb5-workstation
    - libmnl
    - libuuid-devel
    - lm_sensors
    - lsof
    - make
    - mlocate
    - nc
    - ncdu
    - net-tools
    - pkgconfig
    - tar
    - telnet
    - unzip
    - wget
    - vim
    - zip
    - zlib-devel
  Ubuntu:
    - at
    - autoconf
    - automake
    - avahi-daemon
    - avahi-discover
    - avahi-utils
    - cifs-utils
    - cmake
    - cron
    - curl
    - git
    - git-lfs
    - htop
    - keyutils
    - krb5-admin-server
    - krb5-kdc
    - openjdk-11-jdk
    - libboost-dev
    - libkrb5-dev
    - libldap2-dev
    - libmnl-dev
    - libsasl2-dev
    - libxmlsec1
    - libzstd-dev
    - lm-sensors
    - lsof
    - make
    - ncat
    - ncdu
    - net-tools
    - nfs-common
    - pkg-config
    - plocate
    - python3.11-dev
    - smbclient
    - tar
    - telnet
    - unzip
    - uuid-dev
    - wget
    - vim
    - zip
    - zlib1g-dev
  Raspbian:
    - at
    - autoconf
    - automake
    - avahi-daemon
    - avahi-utils
    - cifs-utils
    - cmake
    - cron
    - curl
    - dnsutils
    - fail2ban
    - firewalld
    - git-lfs
    - insserv
    - keyutils
    - libkrb5-dev
    - libldap2-dev
    - libleveldb-dev
    - libsasl2-dev
    - libxml2-dev
    - libxmlsec1-dev
    - libxmlsec1-openssl
    - make
    - pkg-config
    - python3
    - python3-dev
    - python3-pip
    - python3-virtualenv
    - samba
    - smbclient
    - systemd-resolved
    - tmux
    - wget
    - xmlsec1
    - vim
  macOS:
    - autoconf
    - automake
    # - boost
    - brotli
    - cairo
    - clang-format
    - cmake
    - curl
    - dos2unix
    # - flatbuffers
    - gcc
    - gh
    - git
    - git-lfs
    - graphviz
    - hdf5
    - htop
    - jemalloc
    - jsoncpp
    - krb5
    - libev
    - libevent
    - libffi
    - libmagic
    - libpng
    - libpthread-stubs
    - librdkafka
    - libsodium
    - libuv
    - libxml2
    - libxmlsec1
    - lsusb
    - lunchy
    - lz4
    - ncdu
    - ncurses
    - nginx
    - ninja
    - nlohmann-json
    - nmap
    - node
    - nvm
    - open-mpi
    - openjdk@11
    - openldap
    - openssl@1.1
    - pkg-config
    - podman
    - python@3.11
    - rapidjson
    - readline
    - redis
    - ruby
    - rustup-init
    - shyaml
    - snappy
    - sqlite
    - tbb
    - tcl-tk
    - telnet
    - tmux
    - watch
    - wget
    - zeromq
    - zstd
  macOS_casks:
    - appcleaner
    - launchcontrol
  notify: []
