---
packages:
  EL:
    - autoconf
    - automake
    - boost-devel
    - cmake
    - cron
    - curl
    - git
    - git-lfs
    - htop
    - java-11-openjdk-devel
    - krb5-server
    - krb5-workstation
    - libmnl
    - libuuid-devel
    - lm_sensors
    - lsof
    - make
    - mlocate
    - nc
    - ncdu
    - net-tools
    - pkgconfig
    - tar
    - telnet
    - unzip
    - wget
    - vim
    - zip
    - zlib-devel
  Ubuntu:
    - at
    - autoconf
    - automake
    - avahi-daemon
    - avahi-discover
    - avahi-utils
    - cifs-utils
    - cmake
    - cron
    - curl
    - git
    - git-lfs
    - htop
    - keyutils
    - krb5-admin-server
    - krb5-kdc
    - openjdk-11-jdk
    - libboost-dev
    - libkrb5-dev
    - libldap2-dev
    - libmnl-dev
    - libsasl2-dev
    - libxmlsec1
    - libzstd-dev
    - lm-sensors
    - lsof
    - make
    - ncat
    - ncdu
    - net-tools
    - nfs-common
    - pkg-config
    - plocate
    - python3.11-dev
    - smbclient
    - tar
    - telnet
    - unzip
    - uuid-dev
    - wget
    - vim
    - zip
    - zlib1g-dev
  Raspbian: []
  macOS: []
  macOS_casks: []
  notify: []
