---
dependencies:
  - remove-airflow-server
  - remove-airflow-db

galaxy_info:
  role_name: airflow_environment_remove
  author: 1kbgz
  description: Remove airflow prerequisites and virtualenv
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
