---
USERS: []
AUTOMATION_USERS:
  DEV:
    username: svcdev
    uid: 1051
    group: svcdev
    groups: developers,services,staff
    shell: /bin/bash
  PROD:
    username: svcprod
    uid: 1052
    group: svcprod
    groups: developers,services,staff
    shell: /bin/bash

SERVICE_USERS:
  AIRFLOW:
    username: airflow
    uid: 1100
    group: staff
    groups: services,staff
    shell: /bin/bash
  NGINX:
    username: nginx
    uid: 1140
    group: staff
    groups: services,staff
    shell: /bin/bash
  POSTGRES:
    username: postgres
    uid: 1145
    group: staff
    groups: services,staff
    shell: /bin/bash
  REDIS:
    username: redis
    uid: 1155
    group: staff
    groups: services,staff
    shell: /bin/bash

GROUPS:
  - name: developers
    gid: 1200
  - name: admins
    gid: 1201
  - name: services
    gid: 1202
  # NOTE: may need to remap `dialout` and `fax` groups on ubuntu
  - name: staff  # mac
    gid: 20
  - name: sudo
    gid: 21
