---
- name: Create src directory if it does not exist
  ansible.builtin.file:
    path: /opt/src
    state: directory
    mode: '0755'
  become: true

- name: Create repos directory if it does not exist
  ansible.builtin.file:
    path: /opt/repos
    state: directory
    mode: '0755'
  become: true

- name: Create envs directory if it does not exist
  ansible.builtin.file:
    path: /var/lib/envs
    state: directory
    mode: '0755'
  become: true

- name: Create mount directory if it does not exist
  ansible.builtin.file:
    path: /mnt
    state: directory
    mode: '0755'
  become: true

- name: Create local directory if it does not exist
  ansible.builtin.file:
    path: /local
    state: directory
    mode: '0755'
  become: true

- name: Create data mount directory if it does not exist
  ansible.builtin.file:
    path: /data
    state: directory
    mode: '0755'
  become: true
