---
- name: Remove /etc/resolv.conf symlink
  ansible.builtin.file:
    path: /etc/resolv.conf
    state: absent

- name: Link /run/systemd/resolve/resolv.conf to /etc/resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    dest: /etc/resolv.conf
    state: link
  notify: Restart resolved
