---
dependencies:
  - role: base
  - role: airflow_common
  - role: airflow_db

galaxy_info:
  role_name: airflow_server
  author: 1kbgz
  description: Install Apache Airflow server components
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Raspbian
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
