---
- name: Reload daemon files
  ansible.builtin.systemd:
    daemon_reload: true
    force: true

- name: Restart postgresql main
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: postgresql@{{ POSTGRES_VERSION }}-main
