---
- name: Create airflow directory
  ansible.builtin.file:
    path: /var/lib/airflow
    state: directory
    mode: '0775'
    owner: airflow
    group: services
  become: true

# TODO uid here needs to be standardized across servers
- name: Mount airflow lib via nfs
  ansible.posix.mount:
    src: "airflow-sharedrive:/volume1/Developer/var/lib/airflow"
    path: /var/lib/airflow
    opts: "defaults"
    fstype: nfs
    state: mounted
  become: true
  when: "AIRFLOW_LOCATION == 'internal' and OS != 'macOS'"

- name: Create airflow celery dags directory
  ansible.builtin.file:
    path: /var/lib/airflow/dags
    state: directory
    mode: '0775'
    owner: airflow
    group: services
  become: true

- name: Create airflow celery lib directory
  ansible.builtin.file:
    path: /var/lib/airflow/celery
    state: directory
    mode: '0775'
    owner: airflow
    group: services
  become: true

# NOTE: put in /var/lib/airflow for shared mount
- name: Create airflow log directory
  ansible.builtin.file:
    path: /var/lib/airflow/logs
    state: directory
    mode: '0775'
    owner: airflow
    group: services
  become: true

- name: Create airflow scheduler log directory
  ansible.builtin.file:
    path: /var/lib/airflow/logs/scheduler
    state: directory
    mode: '0775'
    owner: airflow
    group: services
  become: true

- name: Create airflow celery log directory
  ansible.builtin.file:
    path: /var/lib/airflow/logs/celery
    state: directory
    mode: '0775'
    owner: airflow
    group: services
  become: true

- name: Set AIRFLOW_HOME for any logins
  ansible.builtin.copy:
    dest: /etc/profile.d/airflow.sh
    content: 'export AIRFLOW_HOME=/var/lib/airflow'
  become: true

- name: Create airflow data directory
  ansible.builtin.file:
    path: /data/airflow
    state: directory
    mode: '0775'
    owner: airflow
    group: services
  become: true

- name: Create airflow home directory
  ansible.builtin.file:
    path: /home/airflow
    state: directory
    mode: '0775'
    owner: airflow
    group: services
  become: true

# TODO MAC
# - name: Mount home shared SMB drive
#   ansible.posix.mount:
#     src: //airflow-sharedrive/Developer/home/airflow
#     path: /home/airflow
#     opts: "rw,vers=3,file_mode=0600,dir_mode=0700,uid=1100,user=airflow,username=airflow,password=airflow"
#     fstype: cifs
#     state: mounted
#   become: true
#   when: "AIRFLOW_LOCATION == 'internal' and OS != 'macOS'"
# - name: Mount data shared SMB drive
#   ansible.posix.mount:
#     src: //airflow-sharedrive/Developer/data/airflow
#     path: /data/airflow
#     opts: "rw,vers=3,file_mode=0600,dir_mode=0700,uid=1100,user=airflow,username=airflow,password=airflow"
#     fstype: cifs
#     state: mounted
#   become: true
#   when: "AIRFLOW_LOCATION == 'internal' and OS != 'macOS'"

- name: Mount home shared nfs drive
  ansible.posix.mount:
    src: "airflow-sharedrive:/volume1/Developer/home/airflow"
    path: /mnt/home/airflow
    opts: "defaults"
    fstype: nfs
    state: mounted
  become: true
  when: "AIRFLOW_LOCATION == 'internal' and OS != 'macOS'"

- name: Mount data shared nfs drive
  ansible.posix.mount:
    src: "airflow-sharedrive:/volume1/Developer/data/airflow"
    path: /data/airflow
    opts: "defaults"
    fstype: nfs
    state: mounted
  become: true
  when: "AIRFLOW_LOCATION == 'internal' and OS != 'macOS'"

- name: Set AIRFLOW_HOME for user
  ansible.builtin.blockinfile:
    path: /home/airflow/.bashrc
    block: |
      source /var/lib/venvs/airflow/bin/activate
      export AIRFLOW_HOME=/var/lib/airflow
    marker: "# {mark} ANSIBLE MANAGED BLOCK - AIRFLOW HOME"
  become: true
  become_user: airflow
