---
- name: Set AIRFLOW_HOME for user
  ansible.builtin.blockinfile:
    path: /home/airflow/.bashrc
    block: |
      source /var/lib/venvs/airflow/bin/activate
      export AIRFLOW_HOME=/var/lib/airflow
    marker: "# {mark} ANSIBLE MANAGED BLOCK - AIRFLOW HOME"
  become: true
  become_user: airflow
