---
- name: Copy airflow config file into place
  ansible.builtin.copy:
    dest: /var/lib/airflow/airflow.cfg
    mode: '0755'
    owner: airflow
    group: services
    content: "{{ lookup('ansible.builtin.template', '../config/airflow.cfg') }}"
  become: true

- name: Copy webserver config file into place
  ansible.builtin.copy:
    dest: /var/lib/airflow/webserver_config.py
    mode: '0755'
    owner: airflow
    group: services
    content: "{{ lookup('ansible.builtin.template', '../config/webserver_config.py') }}"
  become: true

- name: Create airflow venvs directory if it does not exist
  ansible.builtin.file:
    path: /var/lib/venvs/airflow
    state: directory
    owner: airflow
    group: services
    mode: '0755'
  become: true

- name: Copy constraints file
  ansible.builtin.copy:
    src: ../config/constraints-3.12.txt
    dest: /var/lib/venvs/airflow/constraints-3.12.txt
    owner: airflow
    group: services
    mode: '0644'
  become: true

- name: Setup airflow virtualenv
  ansible.builtin.pip:
    requirements: /var/lib/venvs/airflow/constraints-3.12.txt
    virtualenv: /var/lib/venvs/airflow
    virtualenv_python: '3.12'
  become: true
  become_user: airflow

- name: Set AIRFLOW_HOME for user
  ansible.builtin.blockinfile:
    path: /home/airflow/.bashrc
    block: |
      source /var/lib/venvs/airflow/bin/activate
      export AIRFLOW_HOME=/var/lib/airflow
    marker: "# {mark} ANSIBLE MANAGED BLOCK - AIRFLOW HOME"
  become: true
  become_user: airflow

- name: Set AIRFLOW_HOME for user
  ansible.builtin.blockinfile:
    path: /home/airflow/.bashrc
    block: |
      source /var/lib/venvs/airflow/bin/activate
      export AIRFLOW_HOME=/var/lib/airflow
    marker: "# {mark} ANSIBLE MANAGED BLOCK - AIRFLOW HOME"
  become: true
  become_user: airflow
