---
- name: Reload daemon files
  ansible.builtin.systemd:
    daemon_reload: true
    force: true

- name: Restart airflow db
  ansible.builtin.systemd:
    name: "airflow-db"
    state: restarted
    enabled: true
