---
- name: Reload daemon files
  ansible.builtin.systemd:
    daemon_reload: true
    force: true

- name: Restart celery flower
  ansible.builtin.systemd:
    name: "airflow-celery-flower"
    state: restarted
    enabled: true
