---
dependencies: []

galaxy_info:
  role_name: airflow_celery_worker_remove
  author: 1kbgz
  description: Remove airflow_celery_worker and unconfigure
  license: AGPL-3.0
  min_ansible_version: "2.12"
  platforms:
    - name: EL
    - name: Ubuntu
    - name: macOS
  galaxy_tags:
    - development
